### ISSUE TITLE
component customize

### ISSUE THREAD

**Issue by CyberDasein** [dev-family/admiral#111]
Hi. Could you please advise me on how to customize components that are not passed as an attribute to the Admin component? I figured out how to do it with menuPopupExtraComponents, but what if I need to reconfigure the entire footer (sidebar bottom), or the entire sidebar, or all page layout? I couldn't figure it out.

I see that the question of customization has been asked more than once, and it would be great to have a more detailed explanation.

Thanks in advance!

**Comment by aMurashkoWebSecret** [comment]
Hi! Actually we haven't add customising sidebar footer yet. Now you can customise just main content block of the sidebar.
About custom pages:
1. You shout create a new route in «pages» directory and export default there React function component
2. Create routes and call it like a children to Admin component
```

const Routes = createRoutesFrom(import.meta.globEager('../pages/**/*'))

function App() {
    return (
        <Admin><Routes /></Admin>
)
}
```

- If you want to use it with useForm hook - you could wrap it to Form container like this:
```
const FormContainer = (props: IProjectPage) => {
    const { getUpdateFormData, update } = useDataProvider()
    const { route: projectId } = useAppRouter()
    const fetchFormData = async () => await getUpdateFormData(resource, { id: projectId })

    const submitData = async (values) => {
        return await update(resource, { id: projectId, data: values })
    }
    return (
        <Form fetchInitialData={fetchFormData} submitData={submitData}>
            <ProjectPage {...props} />
        </Form>
    )
}
export default FormContainer
```

- If you want to use createCRUD function with custom form fields - you could add it like call React fc:
```
form: {
        create: {
            fields: <Fields />,
        },
        edit: {
            fields: <Fields edit />,
        },
    },
```

Ty for question! We will add sidebar footer to customising in next updates

**Comment by mr-bantsevich** [comment]
Hello @CyberDasein 
Thanks for your interest and your question! Could you please clarify what you want to do with this component? What is missing? It helps us to better understand and build clean architecture.

**Comment by CyberDasein** [comment]
I'm thinking of creating a small web interface with an authorization and data upload feature in the admin area. The data will be used to build graphs and display a dashboard with statistics and results. I haven't finalized anything yet, but your project seems very interesting.

As for the component and customization, the customer can always ask to change anything, which is why I asked the question above. If I notice any shortcomings, I will provide feedback.

Thank you!

**Comment by mr-bantsevich** [comment]
Glad to hear it.

I suppose our demo pages will be useful. Based on your case, if I understood correctly, you can build base CRUD with custom button for upload dataset, like here https://admiral.dev.family/base-crud, and after that, build absolutely custom dashboard using example from this page https://admiral.dev.family/custom-interface.

We'd be happy to help!
