### ISSUE TITLE
Can't to import DateRangePickerInput

### ISSUE THREAD

**Issue by Gorgy** [dev-family/admiral#112]
Hello
I can't to import component DateRangePickerInput from `@devfamily/admiral`
There is no in library 😢 
![image](https://github.com/dev-family/admiral/assets/4216322/9b0686af-f9bd-4a7a-9cf6-9510efe830fc)

**Comment by arturvolokhin** [comment]
Hello, Gordy!
Thanks for your issue.

You are right. 
We added the changes to the master, but didn't update our package.
We have just updated the [@devfamily/admiral](https://github.com/dev-family/admiral) to 5.9.4 version. You should update the version, if you wanna use the DateRangePuckerInput component.

Have a nice day!
