### ISSUE TITLE
Use custom form and rules

### ISSUE THREAD

**Issue by Gorgy** [dev-family/admiral#114]
Hello.
How I can use form with custom rules?
Can I use other UI kit with yours `dataProvider`?
Thank you for for your time.

**Comment by arturvolokhin** [comment]
Good afternoon.
What custom rules are we talking about, could you clarify?

You can wrap the required component in Form component:
```
import { Form, useDataProvider } from '@devfamily/admiral'

const FormContainer = (props: Props) => {
    const { getUpdateFormData, update } = useDataProvider()
    const fetchFormData = async () => await getUpdateFormData('projects', { id: props.id })

    const submitData = async (values: Record<string, unknown>) => {
        return await update('projects', { id: props.id, data: values })
    }
    return (
        <Form fetchInitialData={fetchFormData} submitData={submitData}>
            <ProjectPage {...props} />
        </Form>
    )
}
```

And after that you can use the useForm hook in your wrapped component.



```
const ProjectPage = (props: Props) => {
     const { values, setValues } = useForm()
     return <></>
}
```


As for the DataProvider, you can modify the dataProvider.ts file and add the custom methods, that you can use with the useDataProvider hook. But the methods that are present in this file are initially used under the hood of admiral package, for example, when [creating cruds](https://github.com/dev-family/admiral/blob/master/admiral/crud/index.tsx).

I hope this answer will help you.
