### ISSUE TITLE
use only one action in table ( delete or update )

### ISSUE THREAD

**Issue by tovarish39** [dev-family/admiral#118]
if disable actions (delete and update)
we cat specify "null" to "tableActions" field

export const CRUD = createCRUD({
    path: '/users',
    resource: 'users',
    index: {
        title: 'Users',
        newButtonText: 'Add',
        tableColumns: [...],
        tableActions: null,
    },
    ...
    
   
   how can I make only one of this? delete or update, or custom acion?

**Comment by arturvolokhin** [comment]
Good afternoon, Alexey!

If you don't add the `tableActions` object into the `createCrud` function, the default actions will be used under the hood of admiral.
If you wanna add custom actions, you can use the `render` key to describe your them.

Example:
```
 tableActions: {
            title: 'Actions',
            key: 'actions',
            fixed: 'right',
            width: 140,
            render: (_, record) => {
                return (
                    <div style={{display: 'flex', justifyContent: 'flex-end'}}>
                        <CustomAction id={record.id}/>
                        <DeleteAction resource={resource} id={record.id}/>
                    </div>
                )
            },
        }
```
