### ISSUE TITLE
how can I remove "+ add" button from index page in default index page?

### ISSUE THREAD

**Issue by gorrus39** [dev-family/admiral#119]
how can I remove "+ add" button from index page in default index page?

in this code, I found how change text of button for create record, but how can I remove this button?

```
export const CRUD = createCRUD({
    path: '/users',
    resource: 'users',
    index: {
        title: 'Пользователи',
        newButtonText: 'Add',
        ...

**Comment by arturvolokhin** [comment]
Hello again!
You can do this as follows:
```
export const BaseCRUD = createCRUD({
    actions: <></>,
    ....
```

You can also pass any custom actions. Go to the [page](https://github.com/dev-family/admiral/blob/master/src/crud/base.tsx) to see an example.

**Comment by gorrus39** [comment]
Thanks!)

**Comment by gorrus39** [comment]
Thanks!)
