### ISSUE TITLE
custom pages without auth

### ISSUE THREAD

**Issue by konopkin11** [dev-family/admiral#92]
Я могу создать страницу на подобии визитки, которая будет доступна всем? То есть отключить авторизацию на определенных маршрутах или наоборот сделать саму админ панель только на руте /admin и включить авторизацию только туда?

**Comment by mr-bantsevich** [comment]
No, right now you can't create pages without auth.
But you can create page separately from Admiral, or you can reuse components from Admiral for you page if it needed.

**Comment by konopkin11** [comment]
Ok, I solved it by adding separate router but is it possible to use admin themes in my pages? i see that <Admin> uses ThemeProvider but i cant use it separately i got
`[plugin:vite:import-analysis] Missing "./lib/admiral/theme" export in "@devfamily/admiral" package`
