### ISSUE TITLE
how to customize Login page?

### ISSUE THREAD

**Issue by konopkin11** [dev-family/admiral#93]
and move it to other location like "/adminLogin/"

**Comment by mr-bantsevich** [comment]
You can customize or create your own theme, see section in documentation https://github.com/dev-family/admiral#custom-theme. Is it enough? If not, could you describe what exactly you want to change.
Also logo you can change in logo component which located in src/config/logo

Login URL you can't change. Now we do not see the value in this. I hope we implement this feature in future.
